name: CI Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        needs: setup-node
        run: npm install

      - name: Run lint
        needs: Install dependencies
        run: npm run lint

      - name: Run tests
        needs: Run lint
        run: npm run test
      
      - name: Build
        needs: Run tests
        run: npm run build