name: CI Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: install-dependencies
        needs: setup-node
        run: npm install

      - name: lint
        needs: install-dependencies
        run: npm run lint

      - name: tests
        needs: lint
        run: npm run test
      
      - name: Build
        needs: tests
        run: npm run build